name: oscw
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ---------------------- BLoC State Management ----------------------
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # ---------------------- Dependency Injection -----------------------
  get_it: ^7.6.4

  # ---------------------- Local Storage ------------------------------
  shared_preferences: ^2.3.1

  # ---------------------- Connectivity + Internet Check --------------
  connectivity_plus: ^5.0.2

  # ---------------------- Localization -------------------------------
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # ---------------------- JSON Handling ------------------------------
  json_annotation: ^4.9.0
  image_picker: ^1.2.1
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # JSON model generator (optional but recommended)
  build_runner: ^2.4.11
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    # JSON Localization Files
    - assets/logo/
    - assets/icons/
    - assets/images/
    - lib/core/localization/l10n/en.json
    - lib/core/localization/l10n/hi.json
    - lib/core/localization/l10n/or.json

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-VariableFont.ttf
        - asset: assets/fonts/NotoSans-ItalicVariableFont.ttf
          style: italic
